import type { Metadata } from "next";
import { Inter, PT_Serif, Poppins, Orbitron } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import { AuthProvider } from "../context/AuthContext";
import { LoaderProvider } from "../context/LoaderContext";
import { GlobalLoader } from "../components/GlobalLoader/GlobalLoader";
import { Toaster } from "sonner";

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700"],
});

const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

const poppinsSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700"],
});

const orbitronDisplay = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Avionix Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interSans.variable} ${ptSerif.variable} ${poppinsSans.variable} ${orbitronDisplay.variable}`}
    >
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className="min-h-screen flex flex-col antialiased">
        <LoaderProvider>
          <AuthProvider>
            <Header />
            <GlobalLoader />
            <Toaster richColors position="bottom-right" />
            <main className="flex flex-1">{children}</main>
          </AuthProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}
